// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using personnel_department_DB;

#nullable disable

namespace personnel_department_DB.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230917140849_AddTransferTable")]
    partial class AddTransferTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("personnel_department_DB.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b70e6c6-c0f3-47af-92bb-e3827384f71c"),
                            Name = "ООО Рубик экспресс"
                        });
                });

            modelBuilder.Entity("personnel_department_DB.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptanceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Allowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfPreparation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba624155-2f35-4b0e-a27a-6b090b3f3057"),
                            AcceptanceDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Allowance = 2000m,
                            CompanyId = new Guid("8b70e6c6-c0f3-47af-92bb-e3827384f71c"),
                            DateOfPreparation = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("060917a1-6bd1-45c8-88d8-d907e687098b"),
                            Salary = 10000m
                        },
                        new
                        {
                            Id = new Guid("cac5b915-5584-431f-b04f-f06c1fb3f0e0"),
                            AcceptanceDate = new DateTime(2022, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Allowance = 1000m,
                            CompanyId = new Guid("8b70e6c6-c0f3-47af-92bb-e3827384f71c"),
                            DateOfPreparation = new DateTime(2022, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("714e614a-8cb2-4c44-9171-22a8885f0f18"),
                            Salary = 60000m
                        });
                });

            modelBuilder.Entity("personnel_department_DB.Models.Dismissal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfDismissal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfPreparation")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Pay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.ToTable("Dismissals");
                });

            modelBuilder.Entity("personnel_department_DB.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FamilyComposition")
                        .HasColumnType("bigint");

                    b.Property<long>("INH")
                        .HasColumnType("bigint");

                    b.Property<long>("PassportId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfResidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("WorkExperience")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Employess");

                    b.HasData(
                        new
                        {
                            Id = new Guid("060917a1-6bd1-45c8-88d8-d907e687098b"),
                            DateOfBirth = new DateTime(2003, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FIO = "Василий Петрович Вознесенский",
                            FamilyComposition = 2L,
                            INH = 1234567890L,
                            PassportId = 11148L,
                            PhoneNumber = "+7 919 922 32 23",
                            PlaceOfResidence = "Пр.Мира 1",
                            PositionId = new Guid("886ff80c-a37f-4e08-874f-e29331f0df7c"),
                            WorkExperience = 12L
                        },
                        new
                        {
                            Id = new Guid("714e614a-8cb2-4c44-9171-22a8885f0f18"),
                            DateOfBirth = new DateTime(2001, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FIO = "Владимир Сергеевич Алханчуртов",
                            FamilyComposition = 3L,
                            INH = 1292374892L,
                            PassportId = 22233L,
                            PhoneNumber = "+9 123 653 12 22",
                            PlaceOfResidence = "Пр.Коста 1",
                            PositionId = new Guid("1f62fce3-dd28-4b3e-ae76-35574b009271"),
                            WorkExperience = 7L
                        });
                });

            modelBuilder.Entity("personnel_department_DB.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("886ff80c-a37f-4e08-874f-e29331f0df7c"),
                            Name = "Директор"
                        },
                        new
                        {
                            Id = new Guid("1f62fce3-dd28-4b3e-ae76-35574b009271"),
                            Name = "Бухгалтер"
                        });
                });

            modelBuilder.Entity("personnel_department_DB.Models.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewWork")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousWork")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("personnel_department_DB.Models.WorkingTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActualDaysWorked")
                        .HasColumnType("int");

                    b.Property<int>("BusinessTrip")
                        .HasColumnType("int");

                    b.Property<int>("DaysOff")
                        .HasColumnType("int");

                    b.Property<int>("DaysWorked")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SickLeave")
                        .HasColumnType("int");

                    b.Property<int>("Vacation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("WorkingTime");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74827e20-e7fc-4a0d-b276-62f7304d4fa0"),
                            ActualDaysWorked = 20,
                            BusinessTrip = 4,
                            DaysOff = 4,
                            DaysWorked = 31,
                            EmployeeId = new Guid("060917a1-6bd1-45c8-88d8-d907e687098b"),
                            SickLeave = 3,
                            Vacation = 0
                        },
                        new
                        {
                            Id = new Guid("047a66c3-a0f4-43b0-91ec-d5255e417712"),
                            ActualDaysWorked = 17,
                            BusinessTrip = 4,
                            DaysOff = 7,
                            DaysWorked = 31,
                            EmployeeId = new Guid("714e614a-8cb2-4c44-9171-22a8885f0f18"),
                            SickLeave = 3,
                            Vacation = 0
                        });
                });

            modelBuilder.Entity("personnel_department_DB.Models.Contract", b =>
                {
                    b.HasOne("personnel_department_DB.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("personnel_department_DB.Models.Employee", "Employee")
                        .WithOne("Contract")
                        .HasForeignKey("personnel_department_DB.Models.Contract", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("personnel_department_DB.Models.Dismissal", b =>
                {
                    b.HasOne("personnel_department_DB.Models.Employee", "Employee")
                        .WithOne("Dismissal")
                        .HasForeignKey("personnel_department_DB.Models.Dismissal", "EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("personnel_department_DB.Models.Employee", b =>
                {
                    b.HasOne("personnel_department_DB.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("personnel_department_DB.Models.Transfer", b =>
                {
                    b.HasOne("personnel_department_DB.Models.Employee", "Employee")
                        .WithMany("Ttransfers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("personnel_department_DB.Models.WorkingTime", b =>
                {
                    b.HasOne("personnel_department_DB.Models.Employee", "Employee")
                        .WithOne("WorkingTimeTable")
                        .HasForeignKey("personnel_department_DB.Models.WorkingTime", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("personnel_department_DB.Models.Employee", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("Dismissal");

                    b.Navigation("Ttransfers");

                    b.Navigation("WorkingTimeTable");
                });

            modelBuilder.Entity("personnel_department_DB.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
